name: Execute UI Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn --batch-mode --update-snapshots verify

      - run: mkdir output && cp target/spark-reports/Index.html output/result.html

      - name: Upload test result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: TestReport
          path: output