name: Execute UI Tests

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn test

      - run: mkdir output && cp target/spark-reports/Index.html output/result.html

      - name: Upload test result as artifact
          uses: actions/upload-artifact@v3
          with:
            name: TestReport
            path: output