name: Execute UI Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start Docker Firefox standalone service
        run: docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-firefox:latest

      - name: Run tests with Maven
        run: mvn -B package --file pom.xml

      - run: mkdir output && cp target/spark-reports/Index.html output/result.html

      - name: Upload test result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: TestReport
          path: output